remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: nlaredo.github.io pages
description: A random collection of mostly javascript experiments

google_analytics: G-J4DSMHX8B7
